json.id product.id 
json.name product.product_name
json.price product.product_price
json.image_url product.image_url
json.description product.product_description
json.created_at product.created_at 
json.updated_at product.updated_at
json.is_discounted? product.is_discounted?
json.tax product.tax
json.total product.total
json.supplier product.supplier
json.images product.images 